### ISSUE TITLE
Xaero's Crash after adding Harmonia to AoF7 Modpack

### ISSUE THREAD

**Issue by Leonxilofin** [wasabiwhisper/harmonia#1]
Ever since adding Harmonia there seems to be a random chance my game will crash when changing dimensions or logging out.

The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Xaero's World Map (1.20_1.38.1_fabric) has crashed! Please report here: bit.ly/XaeroWMIssues

[crash-2024-04-13_22.19.30-client.txt](https://github.com/wasabiwhisper/harmonia/files/14969589/crash-2024-04-13_22.19.30-client.txt)

**Comment by wasabiwhisper** [comment]
Thanks for sharing your log. The crash should be resolved in the latest version 1.0.2. It happens indeed when changing dimensions or logging out.
