### ISSUE TITLE
Publishing the mod to Modrinth

### ISSUE THREAD

**Issue by SerenModz21** [wasabiwhisper/harmonia#3]
Hi! I was just wondering if there would be any consideration of the mod being uploaded to Modrinth?

**Comment by invaild-user** [comment]
I would like to see it on modrinth as well, since curseforge is kind of iffy.

**Comment by wasabiwhisper** [comment]
Technically it is possible. Was wondering if there is a specific reason for it to be uploaded to modrinth?

**Comment by SerenModz21** [comment]
Its more or less to be able to stick to using Modrinth for all my mods. Though, i think it might benefit you as it could help spread the mod to more people. I hope this makes sense as I was struggling to get the right words for the previous sentence. In addition, I think it would be nice just to have it on Modrinth with the rest of the Odyssey suite.

**Comment by invaild-user** [comment]
As Seren mentioned, "stick to using Modrinth." This approach allows us to either stay directly on Modrinth's website or use launchers that integrate Modrinth for accessing mods. It's widely acknowledged that CurseForge has less stringent content moderation, which increases the risk of encountering malicious "smaller" mods, though this is not to suggest that yours is.

**Comment by wasabiwhisper** [comment]
Thank you both for the clarification.
I understand the request and the reasoning. 

I have issued a new project on Modrinth. it is currently under review. I will keep you posted about its status. 😄

**Comment by SerenModz21** [comment]
Thank you so much! I really do appreciate it.

**Comment by invaild-user** [comment]
/mods/harmonia ? is gonna be the url ?

**Comment by SerenModz21** [comment]
Modinth has now published the mod https://modrinth.com/mod/wasabiwhisper-harmonia so the issue can now be closed. Thank you again @wasabiwhisper!
